name: drink_water
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^3.0.3
  build_runner: ^2.4.6
  flutter_gen_runner: 5.10.0
  flutter_svg: ^2.1.0


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  provider: ^6.1.4

flutter_gen:
  assets:
    enabled: true
    package_parameter_enabled: true
    line_length: 80
    output: lib/gen/assets.gen.dart 

flutter:
  assets:
    - assets/icons/
    
fonts:
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
